package com.boxy.authenticator.domain.models.enums

enum class ThumbnailIcon(val label: String, val path: String) {
    AMAZON("Amazon", "amazon.png"),
    ATLASSIAN("Atlassian", "atlassian.png"),
    BITBUCKET("Bitbucket", "bitbucket.png"),
    BITWARDEN("Bitwarden", "bitwarden.png"),
    CLOUDFLARE("Cloudflare", "cloudflare.png"),
    COINDCX("CoinDCX", "coindcx.png"),
    DASHLANE("Dashlane", "dashlane.png"),
    DISCORD("Discord", "discord.png"),
    DOCKER("Docker", "docker.png"),
    EVERNOTE("Evernote", "evernote.png"),
    EXPO_GO("Expo Go", "expo_go.png"),
    FACEBOOK("Facebook", "facebook.png"),
    FIGMA("Figma", "figma.png"),
    FIREFOX("Firefox", "firefox.png"),
    GITHUB("GitHub", "github.png"),
    GODADDY("GoDaddy", "godaddy.png"),
    GOOGLE("Google", "google.png"),
    INSTAGRAM("Instagram", "instagram.png"),
    LINKEDIN("LinkedIn", "linkedin.png"),
    MICROSOFT("Microsoft", "microsoft.png"),
    MONGO_DB("MongoDB", "mongo_db.png"),
    MOZILLA("Mozilla", "mozilla.png"),
    NPM("npm", "npm.png"),
    NVIDIA("NVIDIA", "nvidia.png"),
    OLYMP_TRADE("Olymp Trade", "olymp_trade.png"),
    OPENAI("OpenAI", "openai.png"),
    OUTLOOK("Outlook", "outlook.png"),
    PAYPAL("PayPal", "paypal.png"),
    PROTON("Proton", "proton.png"),
    REDDIT("Reddit", "reddit.png"),
    ROCKSTAR_GAMES("Rockstar Games", "rockstar_games.png"),
    SNAPCHAT("Snapchat", "snapchat.png"),
    TRADING_VIEW("TradingView", "trading_view.png"),
    UPSTOX("Upstox", "upstox.png"),
    UPWORK("Upwork", "upwork.png"),
    X("X", "x.png");
}