[versions]
agp = "8.13.2"
android-compileSdk = "37"
android-minSdk = "26"
android-targetSdk = "37"
androidxSqlite = "2.7.0"
androidx-activityCompose = "1.13.0"
androidx-lifecycle = "2.10.0"
androidx-material3 = "1.14.0"
coilCompose = "3.6.2"
compose-multiplatform = "1.10.3"
compose-androidx = "1.10.5"
diglol-crypto = "0.2.0"
filekit = "0.8.8"
guava = "33.7.1-android"
koin = "4.2.2"
koin-compose = "4.2.2"
kotlin = "2.4.20"
kotlinxCoroutinesCore = "1.11.0"
kotlinxDatetime = "0.8.0"
kotlinxSerializationJson = "1.11.0"
ktorClientCore = "3.5.2"
mokoBiometry = "0.4.0"
navigationCompose = "2.9.2"
preferenceKtx = "1.2.1"
qrKit = "3.0.6"
sqlcipherAndroid = "4.18.0"
sqlDelight = "2.3.2"

[libraries]
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose-androidx" }
androidx-compose-animation-core = { module = "androidx.compose.animation:animation-core", version.ref = "compose-androidx" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-androidx" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose-androidx" }
androidx-compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "compose-androidx" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-androidx" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose-androidx" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose-androidx" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-androidx" }
androidx-compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose-androidx" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-androidx" }
androidx-compose-ui-tooling-data = { module = "androidx.compose.ui:ui-tooling-data", version.ref = "compose-androidx" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-material3 = { group = "com.google.android.material", name = "material", version.ref = "androidx-material3" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
diglol-crypto-cipher = { module = "com.diglol.crypto:cipher", version.ref = "diglol-crypto" }
diglol-crypto-kdf = { module = "com.diglol.crypto:kdf", version.ref = "diglol-crypto" }
diglol-crypto-random = { module = "com.diglol.crypto:random", version.ref = "diglol-crypto" }
filekit = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
moko-biometry = { module = "dev.icerock.moko:biometry", version.ref = "mokoBiometry" }
moko-biometry-compose = { module = "dev.icerock.moko:biometry-compose", version.ref = "mokoBiometry" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqlcipher-android = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipherAndroid" }
qr-kit = { module = "network.chaintech:qr-kit", version.ref = "qrKit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
